### ISSUE TITLE
 PHP Fatal Error – yii\base\ErrorException

### ISSUE THREAD

**Issue by maxfrischknecht** [unionco/calendarize#1]
Hi!

After adding the plugin via composer, make a calendarize field and adding this field to a channel section entry, I get the following error after trying to save the entry:

`
yii\base\ErrorException: Method unionco\calendarize\models\CalendarizeModel::__toString() must not throw an exception, caught TypeError: Return value of unionco\calendarize\models\CalendarizeModel::__toString() must be of the type string, object returned in /Applications/MAMP/htdocs/wortstellwerk/vendor/craftcms/cms/src/helpers/StringHelper.php:0
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
`

**Comment by fvaldes33** [comment]
@maxfrischknecht,

Thank you for reporting this bug. Updated the schema version along with a migration to fix this issue. Seemed to be an issue with null values and table columns being `ALLOW NULL` false.

Fixed on 1.1.8 [683f0fd](https://github.com/unionco/calendarize/commit/f8a703d357afe524c2b7a0b6b57997018d05d968)
