### ISSUE TITLE
Reverting entry to previous version causes calendarize field data to be lost.

### ISSUE THREAD

**Issue by langlers** [unionco/calendarize#11]
In Craft 3.1.8, if I revert an entry that uses a Calendarize field to a previous version, all the data in the Calendarize field is lost.

**Comment by fvaldes33** [comment]
Thanks for the find.

Fixed [bc7cd42](https://github.com/unionco/calendarize/commit/bc7cd42eb350f942074fdfb8ec8400531e65ce4e)
