### ISSUE TITLE
How to get events for a certain year

### ISSUE THREAD

**Issue by robarov** [unionco/calendarize#14]
How do I accomplish the following:

I have 12 single-day events, all yearly repeating:
- 1 jan 2012
- 1 feb 2012
- 1 mar 2012
- 1 apr 2012
- 1 may 2012
- 1 jun 2012
- 1 jul 2012
- 1 aug 2012
- 1 sep 2012
- 1 oct 2012
- 1 nov 2012
- 1 dec 2012

Now, to get all entries for the year 2023 and display their exact dates:
```
{% set entries = craft.calendarize.between('2023-01-01', '2024-01-01', { section: ['events'] }, 'asc') %}
```
This gets all relevant entries, how to display their dates?
This seems not possible ATM?

**Comment by fvaldes33** [comment]
Give this a try:

In my database I recreated your above events. Yearly repeating single day events. The `between` method returns the occurrences between the correct dates in the `Occurrence` model that acts like a proxy to the entry with the correct `next` occurrence.

```twig
{% set yearStart = '2022-01-01' %}
{% set yearEnd = '2022-12-31' %}
{% set occurrences = craft.calendarize.between(yearStart, yearEnd, { section: ['liveShows'] }) %}
<ul>
    {% for occurrence in occurrences %}
        <li>{{ occurrence.next | date('Y-m-d') }}</li>
    {% endfor %}
</ul>
```

The difference here being that I am accessing the `next` property on the occurrence instead of the `next` property on the calendarize field handle.

```twig

{# this is already preset to match your prior `between` query #}
{{ occurrence.next | date('Y-m-d') }}

vs

{# this does new logic to figure out the very next occurrence based on the RRULE #}
{{ occurrence.calendarHandle.next | date('Y-m-d') }}
```

Let me know if this works.

**Comment by robarov** [comment]
Thanks for the feedback!  
I updated to `1.2.4` with these results:

```
{# this is already preset to match your prior `between` query #}
{{ occurrence.next | date('Y-m-d') }}
```
Returns 2022-01-01 , 2022-02-01 etc...

```
{# this does new logic to figure out the very next occurrence based on the RRULE #}
{{ occurrence.calendarHandle.next | date('Y-m-d') }}
```
Returns 2020-01-01 , 2020-02-01 etc...

After your comment, I now understand this is expected behaviour.
Maybe some more info in the README would be welcome.

**Comment by fvaldes33** [comment]
Thanks for the feedback. I will be updating the read me with some use cases also.
