### ISSUE TITLE
Entry not saving repeating dates, days of week

### ISSUE THREAD

**Issue by richardwiggins** [unionco/calendarize#15]
I've just updated an event which is a repeating (weekly) entry to change/remove some days of the week, but upon saving it's still showing the previously selected days.

Other fields save and update correctly.

**Comment by fvaldes33** [comment]
@richardwiggins - this was a bug introduced when added some other functionality. Fixed in my latest commit. [Commit](https://github.com/unionco/calendarize/commit/cc60568a5df96ed127cd3a7e1c82d08f9fbfc1ae)
