### ISSUE TITLE
Error when revisiting event

### ISSUE THREAD

**Issue by alexr8** [unionco/calendarize#16]
I've been playing around with this plugin (which is exactly what i needed, and looks great!). I saved an event, and when i try to view my entry again in the admin, i get the following error:

![calendarize-screenshot-error](https://user-images.githubusercontent.com/35040195/53109898-cc5fa280-3531-11e9-9c4d-fdbd42799677.jpg)

Unfortunately i can't access the entry to outline all the options i had turned on, but i had added in repeating, an end repeat, date exceptions and time exceptions.

Unsure if related, but typing in a date exception or time exception, gives the day as undefined unless the entry is then saved, at which point the correct day is displayed:

![image](https://user-images.githubusercontent.com/35040195/53110006-03ce4f00-3532-11e9-88f4-866c9ed05f4d.png)

I've tried recreating the error with other entries, and so far i can't (they save fine and i can view them again without issue). I'm not sure if it's some combination of settings i have added, or maybe exception dates being outside the dates the recurring event is running or something like that?

**Comment by fvaldes33** [comment]
@alexr8 - Would it be possible to send me a copy of the db? If not, just the contents of the `calendarize` table in the database?

Thanks

**Comment by fvaldes33** [comment]
@alexr8 - Any update on this?

**Comment by alexr8** [comment]
Hi @fvaldes33 sorry for not feeding back into this. Unfortunately i'd deleted the entry that was causing this and haven't been able to recreate the issue. I'll open a new ticket if it happens again and provide DB as well, but i guess for now you can close this one.
