### ISSUE TITLE
Correct Docs

### ISSUE THREAD

**Issue by myriago** [unionco/calendarize#18]
Can we change documentation from:

`{% set occurrences = event.calendarizeHandle.getOccurrences(limit = 10) %}` 

Which will give error to:

`{% set limit=10 %}
{% set occurrences = event.calendarizeHandle.getOccurrences(limit) %}`

Took me a while till I went through all of the combinations to get it right, lets make it easier for others.

**Comment by fvaldes33** [comment]
@myriago - This has been fixed in the latest commit. Thanks!
