### ISSUE TITLE
Sorting calendarize entries in Craft control panel

### ISSUE THREAD

**Issue by langlers** [unionco/calendarize#19]
Do you have any advice or guidance on making entries sortable by their calendarize start date in the craft control panel? Is this a potential feature that could be built into the plugin?

I've been working off of brandonkelly's suggestion here:
https://github.com/craftcms/cms/issues/2818#issuecomment-422428099

**Comment by fvaldes33** [comment]
@langlers - Not exactly as straight forward as #2818 because the calendarize data lives on a separate table. I have done something similar in the past for other projects. It would look something like this for calendarize field. The code below should work and once I test it a good amount could add it to the plugin.


```php
Event::on(
    Entry::class, 
    Element::EVENT_REGISTER_SORT_OPTIONS, 
    function(RegisterElementSortOptionsEvent $event) {
        $event->sortOptions[] = [
            'label' => 'Calendarize | Start Date',
            'orderBy' => 'calendarize.startDate'
        ];
    }
);

Event::on(
    ElementQuery::class,
    ElementQuery::EVENT_BEFORE_PREPARE,
    function(CancelableEvent $event) {
        $query = $event->sender;
        if ($query instanceof EntryQuery) {
            if (isset($query->orderBy['calendarize.startDate'])) {
                $direction = $query->orderBy['calendarize.startDate'];
                unset($query->orderBy['calendarize.startDate']);
                $query->join[] = ['JOIN', '{{%calendarize}} calendarize', '[[entries.id]] = [[calendarize.ownerId]]'];
                $query->orderBy['calendarize.startDate'] = $direction;
            }
        }
    }
);
```
