### ISSUE TITLE
Feature request: repeat yearly

### ISSUE THREAD

**Issue by janmeeus** [unionco/calendarize#2]
@fvaldes33 
It would be nice to have an extra Repeat Type "Yearly" - for like yearly recurring dates.
e.g. : Holidays, Birth Days…

**Comment by missmatsuko** [comment]
I think every 2 weeks (biweekly) is also a somewhat common one. Maybe there can be a way to add custom repeat rules?

**Comment by fvaldes33** [comment]
@janmeeus @missmatsuko - two great things to add to the roadmap. I think I can add the yearly and biweekly quite simply. For custom repeat rules, I might need to plan out and figure out how to accomplish that. If you have something in mind, feel free to make a pull request.

Will touch back once yearly and biweekly have been added.

**Comment by fvaldes33** [comment]
1.1.9 - Added yearly and biweekly to the repeat options.

@missmatsuko - I will add custom repeat rules to the roadmap. Thanks for the suggestion.

Fix: [187e948](https://github.com/unionco/calendarize/commit/187e9489f1b713322101739328074ef63e3ce86a)
