### ISSUE TITLE
Day of Week recurring entry not working correctly

### ISSUE THREAD

**Issue by rockit360** [unionco/calendarize#20]
I tried to set a recurring event that starts on 04/02/19. The event is supposed to recur on the first Tuesday of each month, however, the plugin reads 04/02/19 as the last Tuesday of the month and 04/09/19 as the first Tuesday of the month. It seems like this is caused by 5 Tuesdays in the same month.

**Comment by fvaldes33** [comment]
@rockit360 - Seems to be a js issue because it seems to load right on initial load/refresh. Looking into this. Thanks!

**Comment by fvaldes33** [comment]
@rockit360 Sorry for the delay. I just pushed up a commit that should fix this issue. 

Commit [29f2643](https://github.com/unionco/calendarize/commit/29f2643036a31f87ee06ccc42fd853958f709671)
