### ISSUE TITLE
How to search entries with calendarize

### ISSUE THREAD

**Issue by missmatsuko** [unionco/calendarize#21]
I'm creating a searchable events listing, but I'm not able to get search working.
Here's a minimal example of what I tried to do in Twig, but I end up with an error.
```
{% set entries = craft.calendarize.upcoming({ section: ['Event'],
search: 'Birthday' }, 'asc|desc') %}
```

And I ended up with this error:
```
Caused by: PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'calendarize44a1a8733e.startDate' in 'where clause'
```

I've got category and date filters working fine, but I haven't been able to get text search working.

**Comment by fvaldes33** [comment]
@missmatsuko - looking into this. I have gone back and forth a few times on how the initial query fetches data from the calendarize table and ties it back in to craft elements. Should have a fix in the next few days. Thanks!

**Comment by fvaldes33** [comment]
Fixed in latest commit.

**Comment by missmatsuko** [comment]
Working great, thank you!
