### ISSUE TITLE
How to show events older than today only?

### ISSUE THREAD

**Issue by angieherrera** [unionco/calendarize#25]
Hi! I've got Calendarize working for part of an Events section on a site. The other section is to show all event prior to today, but paginated. I have it partially working with Craft's paginate tag, but it currently returns ALL entries (as expected).

I'm not sure how to tweak the code to get it to:
1) limit it to events/entries that are older than today (based on the event start date, not the post date)
2) get the events/entries to be ordered in reverse chronological order. 

Any tips?

**Comment by missmatsuko** [comment]
I don't think there's a dedicated function for getting past events, but you could use `craft.calendarize.between()` to get events from a past date up to the current date, and sort them descending. I'm not sure if there's an oldest possible valid date, but I just put 00 for everything and seemed to work:

```
{% set order = 'desc' %}
{% set unique = true %}
{% set sections = ['mySection'] %}
{% set entries = craft.calendarize.between('00-00-00', 'now'|date, { section: sections }, order, unique) %}
```

**Comment by fvaldes33** [comment]
Thanks to [incraigulous](https://github.com/incraigulous) that is now possible. You can pass a date in the past to the `between` method to get older occurrences. Maybe in the future I can add a method `before` that would query all occurrence before a given date.

**Comment by JayBox325** [comment]
> Maybe in the future I can add a method `before` that would query all occurrence before a given date.

I was about to log a ticket for a 'before' method. That would be sweet! But the between method works for now. Cheers

**Comment by fvaldes33** [comment]
The before method is in the roadmap. Will be added soon.
