### ISSUE TITLE
Wording of the repeat frequency field

### ISSUE THREAD

**Issue by missmatsuko** [unionco/calendarize#28]
I was just noticing that the wording of the repeat fields is awkward (for English, anyways):
![Screenshot of the repeats field](https://user-images.githubusercontent.com/17884198/57662919-8d784080-75a6-11e9-8465-7885eb6087f1.png)

"Repeats every **daily**" is incorrect.
"Repeats every **day**" is correct.

Probably better to either:
1. Change the label 'Every' to 'Repeat frequency' (or similar), **OR** 
2. Change the names of the values so they make sense, i.e. day/week/2 weeks/month/year instead of daily/weekly/biweekly/monthly/annually.

I think I would go for option 2 since it's also more clear (no need to explain that biweekly is every 2 weeks rather than 2 times per week, for example).

**Comment by fvaldes33** [comment]
@missmatsuko - i think option 2 is also a better solution. I'll update on my next push. Thanks!

**Comment by fvaldes33** [comment]
Closed with [38775b7](https://github.com/unionco/calendarize/commit/38775b79fbcf7cfa6ac23e0fa54409b254645059)
