### ISSUE TITLE
Option to change time to 15 minute increments and different times for multiple day events

### ISSUE THREAD

**Issue by JayBox325** [unionco/calendarize#30]
Hi,

I have a client that runs single day and two day events. But in the example of the two day events, Day One is 10:15 to 18:00, while Day Two is 10:15 to 16:00.

Would it be possible to have day timings to be set based on how many days an event spans?

Also, as you'll notice above, the days start at 10:15, whereas the plugin currently only has 30 minute increments for the times.

Love the plugin other than this. Just replaced some over-complicated matrix fields.

Thanks!

**Comment by fvaldes33** [comment]
Closed with [38775b7](https://github.com/unionco/calendarize/commit/38775b79fbcf7cfa6ac23e0fa54409b254645059)

**Comment by JayBox325** [comment]
Amazing, thanks @fvaldes33
