### ISSUE TITLE
Changing a day from 'times' to 'all day' doesn't clear the times

### ISSUE THREAD

**Issue by darylknight** [unionco/calendarize#36]
Hey, thank you for this plugin! I'm currently working with it to try and show store opening times.

I have some code which is displaying all the start and end times for event occurences. If that data is changed from having a start/end date to "All Day", the start/end times are still saved, and the front end doesn't correctly update.

Example:
![image](https://user-images.githubusercontent.com/1250017/65372472-6e3a9f80-dc79-11e9-8725-e88e91f6e313.png)
Outputs:
![image](https://user-images.githubusercontent.com/1250017/65372473-7397ea00-dc79-11e9-8181-fe04b82747e8.png)

Change that to the following and save it:
![image](https://user-images.githubusercontent.com/1250017/65372476-7a266180-dc79-11e9-8a37-c47b8a460a77.png)
And it still outputs:
![image](https://user-images.githubusercontent.com/1250017/65372477-80b4d900-dc79-11e9-9325-e12a0d27d7bf.png)

```
// refb
{% set occurrences = store.openingTimes.getOccurrences(10) %} {# limit is optional and defaults to 10 #}
{% set occurrences = store.openingTimes.getOccurrencesBetween('2019-09-01', '2020-10-01', 10) %} {# limit is optional and defaults to 1 #}
{% for occurrence in occurrences %}
	<p>Start: {{ occurrence.start|date('d M Y H:i l') }} / End: {{ occurrence.end|date('d M Y H:i') }}</p>
{% endfor %}
```

**Comment by fvaldes33** [comment]
@darylknight - The occurrence will always be a date time regardless whether it is an all day event or not. I see the point to clear out the times and make them 00:00:00 and end at 11:59:59 but you could also just wrap your output in a conditional to check the `allDay` boolean value.

```twig
{% for occurrence in occurrences %}
    {% if occurrence.allDay %}
        <p>{{ occurrence.start|date('d M Y') }} - Open All Day </p>
    {% else %}
        <p>Start: {{ occurrence.start|date('d M Y H:i l') }} / End: {{ occurrence.end|date('d M Y H:i') }}</p>
    {% endif %}
{% endfor %}
```

The `occurrence.allDay` is currently missing from the `OccurrenceModel.php` but I can easily add that in the next update. For now, you would have to access the field handle first, so something like `occurrence.fieldHandle.allDay` to make that check.

**Comment by darylknight** [comment]
That makes sense - I hadn't thought to use the `allDay` check, thank you!
