### ISSUE TITLE
Entries that span multiple days cannot access end date

### ISSUE THREAD

**Issue by fvaldes33** [unionco/calendarize#6]
@janmeeus - Opening a new ticket for these other issues

When adding a yearly occurrence that lasts several days (e.g. 20-02-2019 to 24-02-2019), I can only display the startDate of the next occurrence ({{ event.calendarizeHandle.next }}), but not the endDate of the next occurrence.

**Comment by fvaldes33** [comment]
Suggestion would be to add a new method `nextEnd` or `nextRange` for example that will return the end date or an object with both the start and end date.

The `nextRange` method would return an object with both the start and end date and used like below:

```
entry.calendarizeHandle.nextRange.startDate.format('format')
entry.calendarizeHandle.nextRange.endDate.format('format')
```

Otherwise, I could change the `next` functionality to work like above but that would not be backwards compatible.

**Comment by robarov** [comment]
Maybe something like this?
```
entry.calendarizeHandle.next.startDate|date('Y-m-d')
entry.calendarizeHandle.next.endDate|date('Y-m-d')
```
Of course, it `.next` should always return the starting date, even if there is no `endDate`.

**Comment by havardlj** [comment]
This currently has me looking for an alternative to Calendarize, too bad, cause it's its only shortcoming for my use

**Comment by havardlj** [comment]
Is there any way of disabling the repeats-part of the calendarize field until this is implemented?

**Comment by fvaldes33** [comment]
@robarov @havardlj @janmeeus 

This has been added in 1.2.12. Take a look at the readme to see how it was implemented.

Commit: [19f4782](https://github.com/unionco/calendarize/commit/19f478208faa0ba0a8147e139e84623d935e456b)
