### ISSUE TITLE
Date format options

### ISSUE THREAD

**Issue by palomamtnez** [unionco/calendarize#68]
is it possible to change the date format to day/month/year rather than month/day/year?

![image](https://user-images.githubusercontent.com/13962572/119412126-8b255100-bd3f-11eb-9b3a-e311975a7df8.png)

**Comment by palomamtnez** [comment]
After reading the Craft documentation, found out that it is a region/language preference :)

> If you go to your user account, click "Preferences", you'll see a "Language" dropdown, which controls the date/time formatting of the Control Panel for you.

**Comment by bengreenbank** [comment]
Hi. I feel this should be re-opened, as you are correct in that changing the date format in preferences changes the field itself, however the 'Next Occurrence' and 'Occurences' section on the right still has the US formatting. I'm guessing that bit was custom code. Please could it follow the profile preferences as well?
