### ISSUE TITLE
Can I access the time and date as separate entities from startDate?

### ISSUE THREAD

**Issue by richardwiggins** [unionco/calendarize#7]
Can I access the time and date as separate entities from startDate?

For example if I add `{{ event.calendarizeHandle.startDate.format('j M Y H:i:s') }}` I get a time of midnight even if a time has not been selected.

**Comment by fvaldes33** [comment]
The `startDate` field is a standard craft DateTime field and returns a `DateTimeHelper::toDateTime` instance. I would suggest to wrap it in a conditional like below:

```
{% if event.calendarizeHandle.allDay %}
    {{ event.calendarizeHandle.startDate.format('j M Y') }}
{% else %}
    {{ event.calendarizeHandle.startDate.format('j M Y H:i:s') }}
{% endif %}
```

**Comment by fvaldes33** [comment]
Closing.
