### ISSUE TITLE
Calendarize plugin compatibility with Craft 4?

### ISSUE THREAD

**Issue by sonoflee** [unionco/calendarize#79]
With the upcoming release of Craft 4, I wanted to check to see whether there are plans to update Calendarize to be compatible ([Craft plugin updating info here](https://craftcms.com/docs/4.x/extend/updating-plugins.htm)).  If possible, it would be great to get an idea of your timeline. Thanks!

**Comment by timoschwarzer** [comment]
Done in #80

**Comment by tomkiss** [comment]
Nice one @timoschwarzer, I'm currently testing this fork on a project, no issues so far!

Is there anyone at UnionCo who could review this PR? @fvaldes33 pretty please? 🥺

**Comment by sonoflee** [comment]
Thank you to @timoschwarzer for the work, and seconding @tomkiss PR review request for @fvaldes33 - much appreciated!

**Comment by fvaldes33** [comment]
Sorry folks! I am no longer at Union. I have let them know about this PR. Not sure open source is top of the list at the moment.

cc: @abryrath @im-ironclad

**Comment by tomkiss** [comment]
Thank you, Franco, it's appreciated 🙌

**Comment by im-ironclad** [comment]
Hey everyone, no promises on timeline but i'll take a look at it this evening. Might be able to get it closed out pre-weekend.

**Comment by tomkiss** [comment]
Any progress on it would be much appreciated Adam, thank you!

**Comment by tomkiss** [comment]
Hey @im-ironclad - Just pinging back on this thread as a polite reminder if there's any chance to look at this PR soon :)

**Comment by sonoflee** [comment]
Hello @im-ironclad: just wanted to check back on this PR - any updates would be appreciated, thank you!

**Comment by abryrath** [comment]
Sorry for the delay. Version 2.0.0 is available in packagist now, which is compatible with Craft 4.
