### ISSUE TITLE
craft.calendarize.upcoming is not working for me

### ISSUE THREAD

**Issue by richardwiggins** [unionco/calendarize#9]
I'm trying to use your standard method for listing upcoming entries like this; `{% set entries = craft.calendarize.upcoming({ section: ['events'] }, 'desc') %}` for I'm getting a Twig runtime error:

> Calling unknown method: craft\elements\db\CategoryQuery::next()

_events_ is the name of the section I'm attempting to list entries from, just to confirm.

**Comment by fvaldes33** [comment]
I can assume that there might be some clashing with field handles during the sorting method. The plugin doesnt/shouldnt interfere with the CategoryQuery at all. Could you supply a copy of your database? If not, just an over view of the fields you are using and how you are using them?

**Comment by richardwiggins** [comment]
Hi, you can download a copy of the [DB here](https://www.dropbox.com/s/xzgfcsinahpi7ur/craft_culturemk30-01-201911-38.sql?dl=0).

**Comment by fvaldes33** [comment]
@richardwiggins - Good find. Fixed in the latest commit.

Fixed [85f8a3e](https://github.com/unionco/calendarize/commit/85f8a3e858139fe3b28f80efa1a29ed1c227095b)
